config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get  'signup',  to: 'users#new'
  post 'signup',  to: 'users#create'
  get  'profile', to: 'users#show'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get  'index',   to: 'events#index'
  get  'create',  to: 'events#new'
  post 'create',  to: 'events#create'
  get  'events',  to: 'events#show'

  resources :events do
    member do
      post :planned_event
      post :cancelled_event
    end
  end

  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendances, source: :event_attendee
  belongs_to :creator, class_name: 'User'

  validates :title, :description, :date, :location, presence: true

  require 'date'

  scope :past, -> { where('date < ?', Date.today) }
  scope :upcoming, -> { where('date >= ?', Date.today) }

  def upcoming?
    Event.upcoming.include?(self)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  include UsersHelper

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  validates :username, presence: true, length: { minimum: 5, maximum: 50 }
  validates :password, presence: true, length: { minimum: 6, maximum: 255 }
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_many :attendances, foreign_key: :event_attendee_id
  has_many :attended_events, through: :attendances
  has_many :created_events, dependent: :destroy, foreign_key: :creator_id, class_name: 'Event'

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :logged_in?

  include EventsHelper
  include SessionsHelper

  def index
    @events = Event.all
    @past = Event.past
    @upcoming = Event.upcoming
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      flash.now[:notice] = 'Event was created successfully!'
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def planned_event
    user = current_user
    @event = Event.find(params[:id])
    @event.attendees << user
    redirect_to user
  end

  def cancelled_event
    user = current_user
    @event = Event.find(params[:id])
    @event.attendees.delete(user)
    redirect_to user
  end

  def destroy
    @event.delete
  end

  private

    def event_params
      params.require(:event).permit(
        :title,
        :description,
        :date,
        :location
      )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      flash[:notice] = 'You have been logged in!'
      redirect_to user_path(user)
    else
      flash.now[:notice] = 'Invalid email/password combination!'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:notice] = 'You have been logged out!'
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:notice] = 'You have been signed up successfully!'
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = current_user.attended_events.upcoming
    @past_events = current_user.attended_events.past
  end

  private

    def user_params
      params.require(:user).permit(
        :username,
        :email,
        :password,
        :password_confirmation
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def upcoming?
    Event.upcoming.include?(self)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    else
      @current_user = nil
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_check.html.erb
<% if @event.upcoming? %>
  <% unless @event.attendees.include?(current_user) %>
    <%= link_to 'Attend', planned_event_event_path(@event), class: "btn btn-primary", method: :post %>
  <% else %>
    <%= link_to 'Cancel Attendance', cancelled_event_event_path(@event), class: "btn btn-danger", method: :post %>
  <% end %>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>

  <div>
    <% if @event.errors.any? %>
      <ul>
        <% @event.errors.full_messages.each do |err| %>
          <li><%= err %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= f.label :title, class: 'label_html' %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :description, class: 'label_html' %>
  <%= f.text_area :description, class: 'form-control' %>

  <%= f.label :date, 'Event Date', class: 'label_html' %>
  <%= f.date_field :date, class: 'form-control' %>
  <%= f.label :location, class: 'label_html' %>
  <%= f.text_field :location, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: 'btn btn-primary form_button' %>

<% end %>

app/views/events/index.html.erb
<div class="container-fluid">

  <div class="row bg_index">
    <h1>All the Events</h1>
    <div class="col-lg-6">
      <h2 class="jumbotron text-center">Upcoming Events</h2>

      <% @upcoming.each do |upcoming| %>
        <div class="gap_btw">
          <div class="row">
            <div class="col-lg-6 event_img">

            </div>
            <div class="col-lg-6 event_img_info">
              <h2><%= link_to upcoming.title, event_path(upcoming) %></h2>
              <h3><%= upcoming.date %></h3>
            </div>
          </div>
          <div class="row event_direction">
            <h4>This event is taking place on the <%= upcoming.date %> at: <%= upcoming.location %></h4>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-lg-6">
      <h2 class="jumbotron text-center">Past Events</h2>

      <% @past.each do |past| %>
        <div class="gap_btw">
          <div class="row">
            <div class="col-lg-6 event_img">

            </div>
            <div class="col-lg-6 event_img_info">
              <h2><%= link_to past.title, event_path(past) %></h2>
              <h3><%= past.date %></h3>
            </div>
          </div>
          <div class="row event_direction">
            <h4>This event has taken place on the <%= past.date %> at <%= past.location %></h4>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/events/new.html.erb
<% provide(:button_text, 'Create') %>
<div class="container-fluid">
  <div class="row formevent">
    <div class="col-lg-5 event_to_see">
      <h2 class="to_create">Create events,<br><span class="to_see">for others to attend</span></h2>
    </div>

    <div class="col-lg-6 event_area">
      <h2 class="create_title">Create an event</h2>
      <%= render 'form' %>
    </div>

  </div>
</div>

app/views/events/show.html.erb
<div class="container bg_event">
  <div class="row">
    <div class="col-md-7 side_img">

    </div>

    <div class="col-md-5 event_info">
      <h2>Event Details</h2>
      <h3>Author: <%= @event.creator.username %></h3>
      <h3>Title: <%= @event.title %></h3>
      <h3>Date: <%= @event.date %></h3>
      <h3>Location: <%= @event.location %></h3>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-7 event_desc">
      <h4>Description: <%= @event.description%></h4>
    </div>

    <div class="col-lg-4">
      <div class="attend">
        <h3>Attendees</h3>
        <% @event.attendees.each do |attendee| %>
          <h3><%= attendee.username %></h3>
        <% end %>
        <%= render 'check' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', :root %></li>
        <li><%= link_to 'Events', index_path %></li>
        <li><%= link_to 'Create Event', create_path if logged_in? %></li>
        <li><%= link_to 'Sign up', signup_path if !logged_in? %></li>
        <li><%= link_to 'Profile', current_user if logged_in? %></li>
        <li><%= link_to 'Log in', login_path if !logged_in? %></li>
        <li><%= link_to 'Log out', logout_path, method: :delete if logged_in? %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="login_error">
      <%= flash.notice %>
    </p>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<%= form_for(@user) do |f| %>

  <div>
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |err| %>
          <li><%= err %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= f.label :username, class: 'label_html' %>
  <%= f.text_field :username, class: 'form-control' %>

  <%= f.label :email, class: 'label_html' %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password, class: 'label_html' %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, 'Confirmation', class: 'label_html' %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:botton_text), class: "btn btn-primary form_button" %>

<% end %>

app/views/static_pages/home.html.erb
<div class="container-fluid">

  <div class="row cover_img">
    <div class="col-lg-12">
      <span class="textover">You wanna hang out this weekend?</span><br />
      <span class="subtextover">Thousand of events are near by</span>
    </div>
  </div>
  <div class="row bg-color">
    <div class="col-lg-4">
      <h1 class="title">Join</h1>
      <h3 class="title_text">Join the community, create your own events</h3>
    </div>
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
      <h1 class="title">Discover</h1>
      <h3 class="title_text">Browse through thousand of upcoming events near you</h3>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:botton_text, 'Sign up') %>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-7">
      <h1 class="info-call">Join<br> <span class="comm">the community</span></h1>
    </div>
    <div class="col-lg-4 form_area">
      <h1 class="top-margin-space">Create Account</h1>
      <%= render 'shared/form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container user-temp">

  <div class="row top-space">
    <div class="col-md-4 color1">
      <div class="profile-img">
        <img src="https://picsum.photos/180/200" alt="Profile Image" class="img-circle">
      </div>
    </div>

    <div class="col-md-6 color2">
      <div class="profile-title">
        <h1>Welcome <%= @user.username %></h1>
        <h4><%= @user.email %></h4>
      </div>
    </div>


  </div>
  <div class="row">
    <div class="col-lg-12 dividing-line">
      <p>Below are your Events</p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 event-title">
      <h2>Created Events</h2>
      <% @user.created_events.each do |event| %>
        <h3><%= link_to event.title, event_path(event) %></h3>
      <% end %>
    </div>

    <div class="col-md-4 event-title">
      <h2>Past Events</h2>
      <% @past_events.each do |past| %>
        <h3><%= past.title %></h3>
      <% end %>

    </div>

    <div class="col-md-4 event-title">
      <h2>Events to Attend</h2>
      <% @upcoming_events.each do |upcoming| %>
        <h3><%= upcoming.title %></h3>
      <% end %>
    </div>
  </div>
</div>